# Generated by Django 4.2.5 on 2023-09-26 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("medical_records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalrecord",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_records",
                to="users.doctorprofile",
            ),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_records",
                to="users.patientprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="medicalrecord",
            index=models.Index(fields=["mrid"], name="medical_rec_mrid_e940e0_idx"),
        ),
        migrations.AddIndex(
            model_name="medicalrecord",
            index=models.Index(
                fields=["created_at"], name="medical_rec_created_3a5a52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicalrecord",
            index=models.Index(
                fields=["updated_at"], name="medical_rec_updated_f2bf78_idx"
            ),
        ),
    ]
