version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:${BACKEND_PORT}
    volumes:
      - .:/src
    env_file:
      - .env
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
    restart: always
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    restart: always
    ports:
      - "5437:5432"

volumes:
  postgres_data:
